GAME_NAME    = 'Subterranean Disease'
GAME_AUTHOR  = 'Lambdanaut.com'
GAME_VERSION = 0.01

SCREEN_WIDTH  = 800
SCREEN_HEIGHT = 600
SCREEN_FPS    = 24

VIDEO_TILE_WIDTH  = 75
VIDEO_TILE_HEIGHT = 75

ANIMATION_LAG_2 = 2
ANIMATION_LAG_3 = 3
ANIMATION_LAG_4 = 4
