from pygame import FULLSCREEN, DOUBLEBUF, HWSURFACE
from pygame.locals import K_w, K_d, K_s, K_a

GAME_NAME    = 'Subterranean Disease'
GAME_AUTHOR  = 'Lambdanaut.com'
GAME_VERSION = 0.01

# SCREEN_RESOLUTION = (3200, 1800)
SCREEN_RESOLUTION = None
SCREEN_FPS        = 24
# SCREEN_DISPLAY    = FULLSCREEN | DOUBLEBUF | HWSURFACE
SCREEN_DISPLAY    = 0

VIDEO_TILE_WIDTH  = 100
VIDEO_TILE_HEIGHT = 100

ANIMATION_LAG_2 = 2
ANIMATION_LAG_3 = 3
ANIMATION_LAG_4 = 4

# CONTROLS
MOVE_UP    = K_w
MOVE_RIGHT = K_d
MOVE_DOWN  = K_s
MOVE_LEFT  = K_a

# MAPS
MAPS_FILEPATH = 'maps/'